dist: trusty
language: node_js
node_js:
- "stable"
addons:
  chrome: stable
before_script:
# ------ Test setup -------#
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g karma # info - http://karma-runner.github.io/0.8/plus/Travis-CI.html
- npm i -g cat
- npm i rxjs

script: 
# Run all tests
- npm run test:all
